import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Footer from '../components/Footer'
import Header from '../components/Header'

export default function EventPage() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sportradar Coding Challenge</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header/>
      <main className={styles.main}>
        <h1>Sportradar Calendar</h1>
      </main>

      <Footer/>
    </div>
  )
}
