import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function EventPage() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sportradar Coding Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Sportradar Calendar</h1>

      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
